# Generated by Django 6.0.2 on 2026-02-26 21:19

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_expires_at_alter_reservation_status'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='reservation_room_id_e0bebf_idx',
        ),
        migrations.AddField(
            model_name='reservation',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'date', 'start_time', 'end_time'], name='reservation_room_id_9bf5f4_idx'),
        ),
    ]
